version: 2.1

jobs:
  build-learning-rxjs:
    working_directory: ~/learning-rxjs
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-rxjs-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: learning-rxjs-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: build
          command: npm run build
      - run:
          name: unit test
          command: npm run test
      - run:
          name: codecov
          command: npm run codecov

workflows:
  version: 2
  learning-rxjs-workflow:
    jobs:
      - build-learning-rxjs
